### ISSUE TITLE
Hey please give the money back

### ISSUE THREAD

**Issue by xiaomaogy** [hathkul/hathkul-ssh.keys#1]
Hi Hathkul, 

I sent you 1000 dollars to buy the fluence reward proof from you. And after I sent you the money you deleted the telegram and disappeared. This is not really good. Please send me a message on telegram: xiaomaogy. 

Best, 

Vincent

**Comment by hathkul** [comment]
dude you probably either were scammed or are a scammer. I didn't sell any reward proofs or whatever, neither am i going to contact some random person in tg. generally if you buy something you should first confirm ownership. i'm sorry for your loss

**Comment by xiaomaogy** [comment]
Ok at this stage I think I got scammed. Thanks for the reply.
